CREATE TABLE CLIENTES (
    IDCLIENTE INT PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    ENDERECO VARCHAR2(100),
    TELEFONE VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(100)
);

CREATE TABLE PRODUTOS (
    IDPRODUTO INT PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    DESCRICAO CLOB,
    VALOR NUMBER(10, 2) NOT NULL,
    TIPO VARCHAR2(20) CHECK(TIPO IN('Pizza', 'Bebida', 'Sobremesa', 'Outro')) NOT NULL
);

CREATE TABLE INGREDIENTES (
    IDINGREDIENTE INT PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    TIPO_INGREDIENTE VARCHAR2(10) CHECK(TIPO_INGREDIENTE IN('Molho', 'Queijo', 'Carne', 'Legume', 'Outros')) NOT NULL
);

CREATE TABLE ESTOQUE (
    ID_INGREDIENTE INT PRIMARY KEY,
    QTD INT,
    DATA_ENTRADA DATE NOT NULL,
    FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTES(IDINGREDIENTE)
);

CREATE TABLE PEDIDOS (
    IDPEDIDO INT PRIMARY KEY,
    ID_CLIENTE INT,
    DATA_PEDIDO DATE NOT NULL,
    STATUS_PEDIDO VARCHAR2(14) CHECK(STATUS_PEDIDO IN('Pendente', 'Entrege', 'Cancelado', 'Preparando', 'Pronto')) NOT NULL,
    VALOR_PEDIDO NUMBER(10,2) NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(IDCLIENTE)
);

CREATE TABLE PEDIDO_PRODUTOS (
    ID_PEDIDO INT,
    ID_PRODUTO INT,
    QUANTIDADE INT NOT NULL,
    PRIMARY KEY (ID_PEDIDO, ID_PRODUTO),
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(IDPEDIDO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(IDPRODUTO)
);

CREATE TABLE FORNECEDORES (
    IDFORNECEDOR INT PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    TELEFONE VARCHAR2(20) NOT NULL,
    ENDERECO VARCHAR2(100),
    EMAIL VARCHAR2(100) NOT NULL
);

CREATE TABLE FORNECEDOR_INGREDIENTE (
    ID_FORNECEDOR INT,
    ID_INGREDIENTE INT,
    CONSTRAINT PK_IDF_IDI PRIMARY KEY(ID_FORNECEDOR, ID_INGREDIENTE),
    VALOR NUMBER(10,2) NOT NULL,
    FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES(IDFORNECEDOR),
    FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTES(IDINGREDIENTE)
);

CREATE TABLE VENDAS (
    IDVENDA INT PRIMARY KEY,
    DATA_VENDA DATE NOT NULL,
    VALOR NUMBER(10,2) NOT NULL
);

CREATE TABLE ENTREGAS (
    IDENTREGA INT PRIMARY KEY,
    ID_PEDIDO INT,
    DATA_ENTREGA DATE NOT NULL,
    STATUS_ENTREGA VARCHAR2(10) CHECK(STATUS_ENTREGA IN('Pendente', 'Em Rota', 'Entregue', 'Falha')) NOT NULL,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(IDPEDIDO)
);

    
    
    
    
    
    
    
    
    